error inside the failure branch works: wrong number of arguments to anon (expects 0, passed 1)
